apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-ops-view
  name: kube-ops-view
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kubeops.deploybytes.com.
spec:
  selector:
    application: kube-ops-view
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
